version: '2'

vars:
  TAG: "{{ default \"latest\" .TAG }}"

tasks:
  build:docker:
    cmds:
      - docker build -t ns3777k/mailcage:{{ .TAG }} .

  build:gox:all:
    cmds:
      - task: build:gox:server
      - task: build:gox:sendmail

  build:gox:sendmail:
    cmds:
      - gox -os="linux darwin windows" -arch="amd64" -output="{{`{{.Dir}}-{{.OS}}-{{.Arch}}`}}" -verbose ./cmd/mcsendmail/...

  build:gox:server:
    deps: [assets]
    cmds:
      - gox -os="linux darwin windows" -arch="amd64" -output="{{`{{.Dir}}-{{.OS}}-{{.Arch}}`}}" -verbose ./cmd/mailcage/...

  build:all:
    cmds:
      - task: build:server
      - task: build:sendmail

  build:sendmail:
    cmds:
      - go build -o mcsendmail ./cmd/mcsendmail/...

  build:server:
    deps: [assets]
    cmds:
      - go build -o mailcage ./cmd/mailcage/...

  assets:
    cmds:
      - packr2 build ui/server.go

  lint:
    cmds:
      - golangci-lint run

  lint:fix:
    cmds:
      - golangci-lint run --fix
