version: '2'

vars:
  TAG: "{{ default \"latest\" .TAG }}"

tasks:
  docker:
    cmds:
      - task: docker:build
      - task: docker:push

  docker:build:
    cmds:
      - docker build -t ns3777k/mailcage:{{ .TAG }} .

  docker:push:
    cmds:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push ns3777k/mailcage:{{ .TAG }}
      - docker tag ns3777k/mailcage:{{ .TAG }} ns3777k/mailcage:latest
      - docker push ns3777k/mailcage:latest

  build:gox:all:
    cmds:
      - task: build:gox:server
      - task: build:gox:sendmail

  build:gox:sendmail:
    cmds:
      - gox -os="linux darwin windows" -arch="amd64" -output="{{`{{.Dir}}-{{.OS}}-{{.Arch}}`}}" -verbose ./cmd/mcsendmail/...

  build:gox:server:
    deps: [assets]
    cmds:
      - gox -os="linux darwin windows" -arch="amd64" -output="{{`{{.Dir}}-{{.OS}}-{{.Arch}}`}}" -verbose ./cmd/mailcage/...

  build:all:
    cmds:
      - task: build:server
      - task: build:sendmail

  build:sendmail:
    cmds:
      - go build -o mcsendmail ./cmd/mcsendmail/...

  build:server:
    deps: [assets]
    cmds:
      - go build -o mailcage ./cmd/mailcage/...

  assets:
    cmds:
      - packr2 build ui/server.go

  lint:
    cmds:
      - golangci-lint run

  lint:fix:
    cmds:
      - golangci-lint run --fix
