openapi: 3.0.0

info:
  title: MailCage V1 API
  version: "1.0.0"
  contact:
    name: Nikita Safonov
    email: ns3777k@gmail.com

tags:
  - name: messages
    description: Operations over messages

components:
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "something bad happened"

paths:
  /api/v1/message:
    delete:
      tags:
        - messages
      parameters:
        - name: id
          in: query
          description: message id
          required: true
          schema:
            type: string
      summary: Deletes message by id
      responses:
        '200':
          description: OK
        '404':
          description: Message not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "message not found"
        '500':
          description: Unexpected storage error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/messages:
    delete:
      tags:
        - messages
      summary: Deletes all messages
      responses:
        '200':
          description: OK
        '500':
          description: Unexpected storage error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
